-- AI Agents Database Setup - Script 4: Research Reports Table
-- Run this script AFTER running 03-leads-table-simple.sql

-- Research Reports Table (for Sage agent outputs)
CREATE TABLE IF NOT EXISTS research_reports (
    id VARCHAR PRIMARY KEY NOT NULL,
    user_id VARCHAR NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lead_id VARCHAR REFERENCES leads(id) ON DELETE CASCADE,
    job_id VARCHAR, -- References agent_jobs but without foreign key constraint
    
    -- Report content
    report_title VARCHAR NOT NULL,
    report_content TEXT NOT NULL, -- HTML content
    report_type VARCHAR DEFAULT 'linkedin_research' CHECK (report_type IN ('linkedin_research', 'company_research', 'market_research')),
    
    -- Metadata
    research_sources JSONB DEFAULT '[]', -- Array of sources used
    confidence_score INTEGER DEFAULT 0 CHECK (confidence_score >= 0 AND confidence_score <= 100),
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_research_reports_user_id ON research_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_research_reports_lead_id ON research_reports(lead_id);
CREATE INDEX IF NOT EXISTS idx_research_reports_job_id ON research_reports(job_id);
CREATE INDEX IF NOT EXISTS idx_research_reports_report_type ON research_reports(report_type);
CREATE INDEX IF NOT EXISTS idx_research_reports_created_at ON research_reports(created_at DESC);

-- Row Level Security (RLS) Policies
ALTER TABLE research_reports ENABLE ROW LEVEL SECURITY;

-- Research Reports Policies
CREATE POLICY "Users can view their own research reports" ON research_reports
    FOR SELECT USING (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

CREATE POLICY "Users can create their own research reports" ON research_reports
    FOR INSERT WITH CHECK (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

CREATE POLICY "Users can update their own research reports" ON research_reports
    FOR UPDATE USING (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

CREATE POLICY "Users can delete their own research reports" ON research_reports
    FOR DELETE USING (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

-- Function for automatic timestamp updates
CREATE OR REPLACE FUNCTION update_research_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for automatic timestamp updates
CREATE TRIGGER update_research_reports_updated_at_trigger
    BEFORE UPDATE ON research_reports
    FOR EACH ROW EXECUTE FUNCTION update_research_reports_updated_at();

-- Add comments for documentation
COMMENT ON TABLE research_reports IS 'Research reports generated by Sage agent';
COMMENT ON COLUMN research_reports.report_content IS 'HTML content of the research report';
COMMENT ON COLUMN research_reports.research_sources IS 'JSON array of sources used for research';

-- Verify the setup
SELECT 'Research Reports table created successfully!' as status;

-- Show table information
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_schema = 'public' 
  AND table_name = 'research_reports'
ORDER BY ordinal_position;
