-- Ensure Research Reports Table Exists with Correct Schema
-- This script creates or updates the research_reports table to match the expected schema

-- Drop and recreate the table to ensure clean schema
DROP TABLE IF EXISTS research_reports CASCADE;

-- Create the research_reports table with the correct schema
CREATE TABLE research_reports (
    id VARCHAR PRIMARY KEY NOT NULL,
    user_id VARCHAR NOT NULL,
    lead_id VARCHAR,
    job_id VARCHAR,
    
    -- Report content
    report_title VARCHAR NOT NULL,
    report_content TEXT NOT NULL, -- HTML content
    report_type VARCHAR DEFAULT 'linkedin_research' CHECK (report_type IN ('linkedin_research', 'company_research', 'market_research')),
    
    -- Metadata
    research_sources JSONB DEFAULT '[]', -- Array of sources used
    confidence_score INTEGER DEFAULT 0 CHECK (confidence_score >= 0 AND confidence_score <= 100),
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_research_reports_user_id ON research_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_research_reports_lead_id ON research_reports(lead_id);
CREATE INDEX IF NOT EXISTS idx_research_reports_job_id ON research_reports(job_id);
CREATE INDEX IF NOT EXISTS idx_research_reports_report_type ON research_reports(report_type);
CREATE INDEX IF NOT EXISTS idx_research_reports_created_at ON research_reports(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE research_reports ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own research reports" ON research_reports
    FOR SELECT USING (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

CREATE POLICY "Users can insert their own research reports" ON research_reports
    FOR INSERT WITH CHECK (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

CREATE POLICY "Users can update their own research reports" ON research_reports
    FOR UPDATE USING (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

CREATE POLICY "Users can delete their own research reports" ON research_reports
    FOR DELETE USING (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

-- Add comments for documentation
COMMENT ON TABLE research_reports IS 'Research reports generated by Sage agent';
COMMENT ON COLUMN research_reports.report_content IS 'HTML content of the research report';
COMMENT ON COLUMN research_reports.research_sources IS 'JSON array of sources used for research';
COMMENT ON COLUMN research_reports.confidence_score IS 'Confidence score from 0-100';

-- Verify the setup
SELECT 'Research Reports table created successfully!' as status;

-- Show final table structure
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_schema = 'public' 
  AND table_name = 'research_reports'
ORDER BY ordinal_position;
